import { OpenApi } from "@samchon/openapi";

import "./ISwaggerSchema";

/**
 * Reusable components in Swagger.
 *
 * `ISwaggerComponents` is a data structure representing content of `components` object
 * in `swagger.json` file generated by Nestia. Note that, this is not an universal
 * structure, but a dedicated structure only for Nestia.
 *
 * @author Samchon
 */
export import ISwaggerComponents = OpenApi.IComponents;
